### PR TITLE
Final

### PR DESCRIPTION
**Pull request by CitrusPanda94**
"I've noticed some of your styles have changed since pulling them down into my dev. This may be because all your styles are scoped and you haven't imported fonts into all style sections?"

Styles have now been fixed. There are two errors left in code but they don't effect the flow of website or anything. Added Tj in front of component names and everything is up with our JS style guide.

### CODE REVIEW

**Comment by ashleighmclaughlin** [comment]
Yay thanks for updating component names. Allgood about the errors, I will keep an eye on them when I merge.

**Comment by CitrusPanda94** [comment]
Thanks Ashleigh!!!

**Comment by ashleighmclaughlin** [comment]
I noticed your component naming was not fully complete so I updated these for you!

**Comment by CitrusPanda94** [comment]
Cheers. Thank you so much for that! I'll merge the changes when I pull upstream.

**Pull request merged**
